recipes = Recipe.create([
  {name: "Apples and Peanut Butter", description: "An easy snack", directions: "Slice up the apple, and spread peanut butter to taste.", recipe_tried: true},
  {name: "Caprese Salad", description: "A simple starter, perfect for summer!", directions: "Slice tomato and mozzarella, and drizzle with oil and vinegar. Add salt and pepper to taste.", recipe_tried: false},
  {name: "Avocado Toast", description: "A healthy way to start your day", directions: "While toast is toasting, slice avocado. Add avocado to toast, and drizzle with oil. Add salt to taste.", recipe_tried: false},
  {name: "Peanut Butter, Jelly, & Banana", description: "Classic with a twist", directions: "Spread peanut butter one one half, jelly on the other, and add sliced bananas on top of the peanut butter!", recipe_tried: false},
  {name: "Spaghetti and Meatballs", description: "A traditional family dinner", directions: "First, add spaghetti to boiling water. Then, shape beef into meatballs and sautee until juices run clear. Once the pasta is cooked, drain excess water, add marinara sauce and meatballs.", recipe_tried: false},
  {name: "Chicken Salad", description: "A healthy version of a classic recipe", directions: "First, shred cooked chicken in a small bowl. Mix in greek yogurt until chicken is completely coated. Then, chop celery, apples, and grapes into small chunks and add to chicken-yogurt mixture. Serve on bread or in a salad.", recipe_tried: false}])

ingredients = Ingredient.create([{name: "Apple", food_group: "Fruit"},
  {name: "Banana", food_group: "Fruit"}, {name: "Chicken", food_group: "Meat"},
  {name: "Mozzarella", food_group: "Dairy"},{name: "Olives", food_group: "Fruit"},
  {name: "Spinach", food_group: "Greens/Vegetables"}, {name: "Lemon", food_group: "Fruit"},
  {name: "Bread", food_group: "Bread/Grains"}, {name: "Peanut Butter", food_group: "Spread"},
  {name: "Jelly", food_group: "Spread"}, {name: "Egg", food_group: "Dairy"},
  {name: "Chocolate", food_group: "Dessert"}, {name: "Carrots", food_group: "Greens/Vegetables"},
  {name: "Avocado", food_group: "Fruit"}, {name: "Marinara", food_group: "Sauces"},
  {name: "Salt", food_group: "Spices/Herbs"}, {name: "Pepper", food_group: "Spices/Herbs"},
  {name: "Oil", food_group: "Oils/Dressings"}, {name: "Vinegar", food_group: "Oils/Dressings"},
  {name: "Beef", food_group: "Meat"}, {name: "Tomato", food_group: "Fruit"},
  {name: "Onion", food_group: "Greens/Vegetables"}, {name: "Pasta", food_group: "Bread/Grains"},
  {name: "Garlic", food_group: "Greens/Vegetables"}, {name: "Blueberries", food_group: "Berries"},
  {name: "Mayonnaise", food_group: "Condiment"}, {name: "Milk", food_group: "Dairy"},
  {name: "Greek Yogurt", food_group: "Dairy"}, {name: "Celery", food_group: "Greens/Vegetables"},
  {name: "Grapes", food_group: "Fruit"}])

recipe_ingredients = RecipeIngredient.create([
  {recipe_id: 1, ingredient_id: 1, quantity: 1, measurement: "apple"},
  {recipe_id: 1, ingredient_id: 9, quantity: 1, measurement: "tbs"},
  {recipe_id: 2, ingredient_id: 4, quantity: 0.25, measurement: "lb"},
  {recipe_id: 2, ingredient_id: 21, quantity: 1, measurement: "tomato"},
  {recipe_id: 2, ingredient_id: 18, quantity: 1, measurement: "tbs"},
  {recipe_id: 2, ingredient_id: 19, quantity: 1, measurement: "tbs"},
  {recipe_id: 3, ingredient_id: 8, quantity: 1, measurement: "slice"},
  {recipe_id: 3, ingredient_id: 14, quantity: 0.5, measurement: "avocado"},
  {recipe_id: 3, ingredient_id: 18, quantity: 1, measurement: "tsp"},
  {recipe_id: 3, ingredient_id: 16, quantity: 1, measurement: "dash"},
  {recipe_id: 4, ingredient_id: 8, quantity: 2, measurement: "slices"},
  {recipe_id: 4, ingredient_id: 9, quantity: 2, measurement: "tbs"},
  {recipe_id: 4, ingredient_id: 10, quantity: 1.5, measurement: "tbs"},
  {recipe_id: 4, ingredient_id: 2, quantity: 0.5, measurement: "banana"},
  {recipe_id: 5, ingredient_id: 15, quantity: 0.5, measurement: "cup"},
  {recipe_id: 5, ingredient_id: 20, quantity: 1, measurement: "serving"},
  {recipe_id: 5, ingredient_id: 23, quantity: 0.25, measurement: "lb"},
  {recipe_id: 6, ingredient_id: 3, quantity: 0.25, measurement: "lbs"},
  {recipe_id: 6, ingredient_id: 28, quantity: 2, measurement: "oz"},
  {recipe_id: 6, ingredient_id: 29, quantity: 0.25, measurement: "cup chopped celery"},
  {recipe_id: 6, ingredient_id: 1, quantity: 0.25, measurement: "cup chopped apple"},
  {recipe_id: 6, ingredient_id: 30, quantity: 5, measurement: "grapes"},])
